# Generated by Django 4.0.1 on 2022-01-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='stripe_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
